### ISSUE TITLE
Automation error due to UTC Offset?

### ISSUE THREAD

**Issue by Lucid881** [TomFrankly/pipedream-notion-recurring-tasks#9]
Hi, first of all, thank you so much for creating this automation! I've been trying to set it up in the last few hours and I keep encountering the same error. I've set up the time zone as Madrid, but I also tried with other timezones with the same issue:  
Error updating UTC Offset:     at null.buildRequestError (/tmp/__pdg__/dist/code/788a1de22ecc007b6904dab5d7c9de8e7365d5484c93ce59a7691596a15f4064/node_modules/.pnpm/@notionhq+client@2.2.15/node_modules/@notionhq/client/build/src/errors.js:162:16)
    at Client.request (/tmp/__pdg__/dist/code/788a1de22ecc007b6904dab5d7c9de8e7365d5484c93ce59a7691596a15f4064/node_modules/.pnpm/@notionhq+client@2.2.15/node_modules/@notionhq/client/build/src/Client.js:378:54)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 {
  name: 'APIResponseError',
  code: 'validation_error',
  status: 400,
  headers: Headers {
    [Symbol(map)]: [Object: null prototype] {
      date: [Array],
      'content-type': [Array],
      'content-length': [Array],
      connection: [Array],
      'x-powered-by': [Array],
      'x-notion-request-id': [Array],
      etag: [Array],
      vary: [Array],
      'cf-cache-status': [Array],
      'set-cookie': [Array],
      server: [Array],
      'cf-ray': [Array]
    }
  },
  body: '{"object":"error","status":400,"code":"validation_error","message":"Type error with formula","request_id":"e1e8a65b-1043-4cf0-a0ee-4b2215cc0475"}'
}
This is the completed log:
<img width="887" alt="image" src="https://github.com/TomFrankly/pipedream-notion-recurring-tasks/assets/167341998/38f3f2b1-f656-4ea4-ba64-9cff6bd65b5d">

Thanks!!

**Comment by TomFrankly** [comment]
@Lucid881 are you using one of my templates, or your own database?

If the latter, I'd guess this is likely an issue on the Notion side. See this reference and video to make sure your UTC Offset property is of the right type (formula): https://thomasjfrank.com/notion-automated-recurring-tasks/#formulas-and-properties

**Comment by TomFrankly** [comment]
@Lucid881 just tested a new setup with Paris as the selected timezone. Here are my logs: 
<img width="783" alt="CleanShot 2024-04-17 at 10 55 05@2x" src="https://github.com/TomFrankly/pipedream-notion-recurring-tasks/assets/684961/cf934905-0803-423c-8829-40c21fa219ac">

If you can open the toggles to show the text in additional screenshots, that'd be helpful!

**Comment by TomFrankly** [comment]
@Lucid881 hmm, I just tested with that exact template and had no issues.

What does your config tab look like?

<img width="852" alt="CleanShot 2024-04-17 at 16 10 56@2x" src="https://github.com/TomFrankly/pipedream-notion-recurring-tasks/assets/684961/8e193e96-a865-4775-ab1c-14aefdfefe15">

I'm a bit confused that your logs initially show all these properties:

<img width="824" alt="CleanShot 2024-04-17 at 16 12 49@2x" src="https://github.com/TomFrankly/pipedream-notion-recurring-tasks/assets/684961/875ca694-f21f-49cf-9801-fb8b535d23fe">

I only have two here initially:

![CleanShot 2024-04-17 at 16 13 22@2x](https://github.com/TomFrankly/pipedream-notion-recurring-tasks/assets/684961/34fcdb3a-fb68-4fbc-9e30-a3f20ce180c9)

This is because that part of the logs only shows properties that had to be configured manually. And that Advanced Recurring Tasks template comes with those properties by default, so the script should recognize them automatically behind the scenes.

Did you happen to rename them?

**Comment by TomFrankly** [comment]
@Lucid881 hmm, your logs also look a bit out of date as well. They don't include that initial "Setting up configs..." message.

Your notion_recurring_tasks step likely has an Update button in the top-right corner of the Config section. Click that if you see it; otherwise, you can try setting up the latest version from scratch: https://thomasjfrank.com/notion-automated-recurring-tasks/#automated-recurring-tasks-pipedream-workflow

**Comment by Lucid881** [comment]
@TomFrankly I renamed the properties but not all. Should I reverse the titles?
This is how my config tab looks like: 
<img width="910" alt="image" src="https://github.com/TomFrankly/pipedream-notion-recurring-tasks/assets/167341998/a1c6147d-e8c4-4c9c-a044-09fb99f42f59">

**Comment by Lucid881** [comment]
@TomFrankly I ran the test again today with a new test event. Here are the logs: 
<img width="902" alt="image" src="https://github.com/TomFrankly/pipedream-notion-recurring-tasks/assets/167341998/d0fb8a4b-a49a-4143-81d2-4136d7f97499">
I'm not sure why I'm getting all this extra properties :(

**Comment by TomFrankly** [comment]
@Lucid881 ok, two things to try:

First, try duplicating a new copy of Ultimate Tasks, just to see if the error has to do with the database you're working with: https://thomasfrank.notion.site/Ultimate-Tasks-for-Notion-982c5dd2b2c24818b58bf5f4f8f04071?pvs=4

If that doesn't work, try creating a new version of the workflow: https://thomasjfrank.com/pipedream-notion-recurring-tasks/ - and target that copy of Ultimate Tasks.

This will guarantee that your setup matches mine, which I know works.

My suspicion is that there's something different about your Notion setup. I can see that your Due property has been renamed to "Caundo?", which shouldn't be a problem, but there might be other changes I can't see that are causing a problem.

**Comment by Lucid881** [comment]
Hi Thomas, thanks! But I'm not using Ultimate Tasks but Advanced Recurring Tasks Dates (2023): https://thomasfrank.notion.site/Advanced-Recurring-Task-Dates-2023-484ab7302d8e43e29d2ca722b287c5e5
Since I already have a task system for projects and this would be a separated one for recurring tasks since those in our case are operational and not tied to projects and the simplicity of the Ultimate Tasks template worked for me. It is it's own database and I didn't change anything about it but the parameters titles.
Yesterday I deleted everything and added again your template and didn't change anything and the test run ok, so I deployed it. I then changed a few of the priorities titles to Spanish (since that's our main working language) and I checked today and the automation didn't run. So I think there is an issue when changing the names of the parameters. I have a suspicion, would symbols and accents (like á) in the parameters name affect the script?

**Comment by TomFrankly** [comment]
It's possible – did you try a test without changing the names first? That would help narrow it down!

**Comment by Lucid881** [comment]
Yes, I did try a test and everything worked perfectly. But I need to change the names since my coworkers are not english speakers so they won't understand the naming conventions.

**Comment by TomFrankly** [comment]
@Lucid881 can you get by just renaming the properties that people will see, such as Due and Next Due?

The other properties essentially run the template from behind the scenes and are not seen very often. Type, UTC Offset, Localization Key, and Next Due API are all hidden in every view.

If changing their names breaks the automation, then I'd recommend leaving them in English. Unfortunately I'm not able to prioritize troubleshooting my automations for non-English use (though if you're a coder, you're welcome to fork this automation and modify it for your own internal use)

**Comment by Lucid881** [comment]
@TomFrankly yes, those are the properties I renamed, I didn't rename all the properties. I will keep the template in english and train the team on the terms. Thanks!
